#!/usr/bin/env php
<?php

require __DIR__ . '/global-inc.php';

$consoleKernel = new \YusamHub\AppExt\SymfonyExt\ConsoleKernel(__DIR__, [
        //'/src/SymfonyExt/Console/Commands' => '\\YusamHub\\AppExt\\SymfonyExt\\Console\\Commands'
]);
$consoleKernel->run();

